server:
  port: 8081

spring:
  datasource:
    url: ${SUPABASE_JDBC_URL}
    username: ${SUPABASE_DB_USERNAME}
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 30000
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
    properties:
      hibernate:
        default_schema: access_profile_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

app:
  jwt:
    secret: ${JWT_SECRET}
  supabase:
    url: ${SUPABASE_URL}
    service-role-key: ${SUPABASE_SERVICE_ROLE_KEY}
    storage:
      portfolio-bucket: ${SUPABASE_STORAGE_BUCKET_PORTFOLIO}
