server:
  port: ${PORT:10000}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:${SUPABASE_JDBC_URL}}
    username: ${SPRING_DATASOURCE_USERNAME:${SUPABASE_DB_USERNAME}}
    password: ${SPRING_DATASOURCE_PASSWORD:${SUPABASE_DB_PASSWORD}}
    driver-class-name: org.postgresql.Driver
    hikari:
      username: ${SPRING_DATASOURCE_USERNAME:${SUPABASE_DB_USERNAME}}
      password: ${SPRING_DATASOURCE_PASSWORD:${SUPABASE_DB_PASSWORD}}
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 30000
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
    properties:
      hibernate:
        default_schema: chat_notification_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

app:
  jwt:
    secret: ${JWT_SECRET}

SERVICE_TOKEN: ${INTERNAL_SERVICE_TOKEN}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
