FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /workspace
COPY pom.xml .
COPY src ./src
RUN mvn -DskipTests package

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /workspace/target/*.jar /app/app.jar
EXPOSE 10000
ENTRYPOINT ["sh","-c","java -Dserver.port=${PORT:-10000} -Dspring.profiles.active=render -jar /app/app.jar"]
